                                                 Basic Numpy Exercises 
                                               Compiled by: Dr. Noman Islam

#### 1. Generate a 1D NumPy array containing numbers from -2 to 2 in increments of 0.2. Use optional start and step arguments of np.arange() function.

In [69]:
import numpy as np
arr_1d = np.arange(-2,2,0.2)
arr_1d


array([-2.0000000e+00, -1.8000000e+00, -1.6000000e+00, -1.4000000e+00,
       -1.2000000e+00, -1.0000000e+00, -8.0000000e-01, -6.0000000e-01,
       -4.0000000e-01, -2.0000000e-01, -4.4408921e-16,  2.0000000e-01,
        4.0000000e-01,  6.0000000e-01,  8.0000000e-01,  1.0000000e+00,
        1.2000000e+00,  1.4000000e+00,  1.6000000e+00,  1.8000000e+00])

#### 2. Generate another 1D NumPy array containing 11 equally spaced values between 0.5 and 1.5. Extract every second element of the array

In [70]:
arr1_1d = np.linspace(0.5,1.5,11)
arr1_1d

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5])

#### 3. Create a 4x4 array with arbitrary values.Extract every element from the second row.


In [71]:
arr2 = np.empty((4,4))
arr2


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
arr2_extr = arr2[1:2]
arr2_extr

array([[1., 1., 1., 1.]])

#### 4. Extract every element from the third column

In [73]:
third_col_elem = arr2[0:4,2]
third_col_elem

array([1., 1., 1., 1.])

#### 5. Assign a value of 0.21 to upper left 2x2 subarray.

In [74]:
arr3 = np.zeros((2,2))
print(arr3)

[[0. 0.]
 [0. 0.]]


In [75]:
arr3[0,0]=0.21
arr3

array([[0.21, 0.  ],
       [0.  , 0.  ]])

#### 6. Read an 2D array from the file exercise1_4.dat. You can usethe function np.loadtxt():
data = np.loadtxt(‘exercise1_4.dat’)

#### Split the array into four subblocks (upper left, upper right, lower left, lower right) using np.split(). Construct then the full array again with np.concatenate(). You can visualize the various arrays with matplotlib’s imshow(), i.e. import pylab pylab.imshow(data)